### ISSUE TITLE
Can't find and open the data browser

### ISSUE THREAD

**Issue by Robotdog0** [stephanlphilips/core_tools#16]
Thank you for sharing this very useful measurement tool, which is really a great job ! 
I encounter a problem: when I refer to the section "Starting up the GUI" in the docs (https://core-tools.readthedocs.io/en/latest/), I can't find  "data_browser.py" from "core_tools.data.gui" folder. Similarly, the GUI can't be opened using "ct.launch_databrowser()".  I will be grateful if you can reply to me. But if it is not convenient for you, feel free to refuse me. I can understand it. Thanks.

**Comment by sldesnoo-Delft** [comment]
The documentation is really out-of-date. Sorry for that.

You can launch the GUI with:

```Python
from core_tools.startup.databrowser import databrowser_main

databrowser_main()
```

To use ```ct.launch_databrowser()``` you have to use the configuration file. See 
https://github.com/stephanlphilips/core_tools/blob/master/examples/demo_station/startup_laptop.py

**Comment by sldesnoo-Delft** [comment]
If you want to launch the data browser without the YAML file use the following code:

```Python
from core_tools.data.gui.qml.data_browser import data_browser

browser_instance = data_browser()
```

**Comment by Robotdog0** [comment]
Solved, that works! Thank you so much for your help~
